### ISSUE TITLE
Can you add a list of the most metall words?

### ISSUE THREAD

**Issue by giggity-hub** [lucone83/deep-metal#7]
Howdy
I'd like to do make a "metal typing test" and i need some metal words. 
Your metalness score is perfect but i'd need more than the 20 words from the Analysis Notebook.
If you could upload a file with like the 5000 most metal words that'd be splendid.

cheers 🤘

**Comment by lucone83** [comment]
Here you go :)

[high_metalness_words.zip](https://github.com/lucone83/deep-metal/files/6394146/high_metalness_words.zip)

**Comment by lballore** [comment]
Here you go 🤘🏼 

[high_metalness_words.zip](https://github.com/lucone83/deep-metal/files/6394151/high_metalness_words.zip)
